import React from "react";

const HomePage = () => {
  return (
    <>
      {/* <div class="header">
        <p class="student-name">Chau Bui</p>
        <nav>
          <a class="nav-button" href="index.html">
            {" "}
            Home
          </a>
          <a class="nav-button" href="contact.html">
            Contact
          </a>
          <a class="nav-button" href="gallery.html">
            Gallery
          </a>
          <a class="nav-button" href="order.html">
            Order
          </a>
          <a class="nav-button" href="staff.html">
            Staff
          </a>
        </nav>
      </div> */}

      <h1>Web Development Concepts</h1>
      <article>
        <h3>About Web Servers</h3>
        <p>
          An index file is the default webpage automatically generated by the
          server and can contains all the files and links to that directory. For
          example, if a user doesn't request a specific file when visiting a
          webpage, by default the web server will direct the user to the index
          file. I created the index.html by creating a new file in VS Code with
          HTML as an extension and saving it to a folder in my local hard drive.
          I added HTML boiler plate using Emmet Abbreviation.
        </p>

        <p>
          The browser inspector tools allows us to view the local file in the
          web browser. It also contains information such as the file name,
          status code, type, the HTTP request, and response. The page index.html
          has the following: The request line starts with request method GET,
          typically used for requesting or receiving a resource. The status code
          is 200 and the reason-phrase is "OK" which indicates the request was
          successful. The status code is followed by Response Headers which
          contains the Content-type (key:value pairs): text/html, indicate the
          format of the resource as a response for the browser. Last modified
          date property which tells the date and time the document was last
          modified.
        </p>

        <p>
          The difference about the file's details on web server vs local server
          is the the URL which has HTTPS: as the protocol, the subdomain
          "web.engr" and the host domain "oregonstate.edu". The subdomain tells
          us about a separate section of a webpage dedicated to it's own
          content. It can includes: directories, formatting and others unique
          contents. The resource is now leading to the HTML file /a1-username.
          The response header contains additional information such as the
          content-type: text/html. The server: Apache/2.4.6. The date.
          Content-Length. The favicon.co file has a status code 200 OK,
          indicating the request has succeeded. The favicon.ico file has the
          status of 200 indicate the request was successful. But, main.css and
          main.js has "404 Not found" meaning that the server is reachable but
          the specific page is not there, could be either broken or no longer
          exists.
        </p>

        <p>
          The schema can be identified as "HTTPS:" a secured version of HTTP.
          This protocol allows encrypting of sensitive information such as
          credit card numbers, passwords, and personal information. The
          subdomain is "web.engr" is use for separating a website into sections
          and the host domain is "oregonstate.edu" which is the main website.
          The resource in this case is /a1-username which point to the
          index.html file.
        </p>
      </article>
      <article>
        <h3>Frontend Design</h3>
        <p>
          Frontend design is the concept of combining the graphic design and the
          user interface to create the most appropriate user experience.
          Frontend designers typically work on creating a website, or an
          application, that implements the visual, color, photography,
          navigation system, themes, etc. Frontend design also responsible with
          implementing the quality of user experience to make sure the product
          is effective and easy to use.
        </p>
        <dl>
          <dt>Effective</dt>
          <dd>
            How effective is the end result and if the product useful and helps
            the user achieve their goal?
          </dd>
          <dt>Efficient</dt>
          <dd>
            Referring to the speed of which work can be done using the product.
            How effective it is without wasting too much time.
          </dd>
          <dt>Easy to navigate</dt>
          <dd>
            Referring to the ease of use when the user is engaging with the
            product, how easy it is to navigate, search and remember.
          </dd>
          <dt>Error-free</dt>
          <dd>
            How efficient is the product in preventing errors and dealing with
            recovery if the user accidentally made a mistake.
          </dd>
          <dt>Enjoyable</dt>
          <dd>
            Describing the overall experience of the user. How satisfied were
            they with the content and design of the application.
          </dd>
        </dl>
        <p>
          There are multiple layout tags, including:
          <strong> header, nav, main, section, article, footer</strong> etc. The
          purpose of page layout tags is to help the user navigate through the
          application easily. The <strong>header</strong> tag typically
          describes the banner of the page, this could include the name or
          marketing slogan. The <strong>nav</strong> tag served as navigation
          for the user to navigate through the webpage, this typically includes
          menu, search, or links etc. The <strong>main</strong> tag describes
          the block that holds the main content on the webpage. The
          <strong>section</strong> tag is used for grouping of content, it
          defines a section in a document. The <strong>article</strong> tag
          describes a single specific topic in the document. The
          <strong>footer</strong> tag typically reside at the bottom of the page
          and usually holds legal information, contact information and links.
        </p>
        <p>
          Anchors link content from page to page using anchor tags with href
          attribute. We can create anchor tags to specify the hyperlink to a
          source or an destination. The anchor tags uses "href" attribute to
          specify a target/destination.
        </p>
      </article>
    </>
  );
};

export default HomePage;
